/**
 * Central catalogue of user-facing copy. Keeping strings here lets
 * `tests/no-advice.test.ts` scan every template in one place and guarantees the
 * product never renders investment advice.
 */
export const COPY = {
  appName: "MarketPulse",
  tagline: "Real-time stock news intelligence",
  principle: "Evidence, not instructions.",
  legend:
    "Green/red show measured price movement. MarketPulse provides evidence, not instructions.",
  disclaimer:
    "MarketPulse presents observable market evidence about events and reactions. It does not provide investment advice or instructions.",

  nav: {
    dashboard: "Dashboard",
    watchlists: "Watchlists",
    alerts: "Alerts",
    macro: "Macro",
    replay: "Replay",
    about: "About",
  },

  common: {
    loading: "Loading",
    stale: "stale",
    live: "live",
    retry: "Retry",
    refresh: "Refresh",
    noData: "No data",
    notAvailable: "not available",
    empty: "Nothing here yet.",
    errorTitle: "Something went wrong",
    errorBody: "The data source did not respond. Showing the last known state.",
    seeEvent: "View detail",
    justNow: "just now",
  },

  dashboard: {
    title: "Ranked event feed",
    subtitle: "Sorted by measured impact, not chronology.",
    leftRail: "Watchlists & filters",
    sectors: "Sectors",
    macro: "Macro pulse",
    watchlist: "Watchlist",
    alerts: "Recent alerts",
    indices: "Indices",
    session: "Session",
    pipelineTick: "Pipeline",
    health: "Health",
    regime: "Regime",
    staleNotice: "Feed is stale — last successful refresh shown.",
    filterAll: "All",
  },

  eventCard: {
    impact: "Impact",
    relevance: "Relevance",
    sentiment: "Sentiment",
    sincePublication: "since publication",
    articles: "articles",
    source: "Source",
  },

  detail: {
    backToFeed: "Back to feed",
    overview: "Overview",
    whatHappened: "What Happened",
    whyItMatters: "Why It Matters",
    expectationVsActual: "Expectation vs Actual",
    priceReaction: "Price Reaction",
    volumeReaction: "Volume Reaction",
    sectorReaction: "Sector Reaction",
    relatedStocks: "Related Stocks",
    technicalContext: "Technical Context",
    macroContext: "Macro Context",
    optionsContext: "Options Context",
    timeline: "Timeline",
    sources: "Sources",
    impactBreakdown: "Impact Score Breakdown",
    intraday: "Intraday",
    direct: "direct",
    correlated: "correlated",
    optionsUnavailable: "Options data unavailable",
    noSources: "No linked sources.",
    expectationNote: "Consensus figures are as of the latest available estimate period.",
    atPublication: "At publication",
    daily: "Daily",
    volume: "Volume",
    rvol: "RVOL",
    vwap: "VWAP",
    atr: "ATR",
    gap: "Gap",
    peak: "Peak 60m",
    trough: "Trough 60m",
    expected: "Expected",
    actual: "Actual",
    cumulative: "Cumulative",
    expectedToDate: "Expected to date",
    profile: "Profile",
    sectorEtf: "Sector ETF",
    etfChange: "ETF change",
    stockVsEtf: "Stock vs ETF",
    peers: "Peers",
    condition: "conditions",
    noConditions: "No notable technical conditions.",
    iv: "Implied volatility",
    ivChange: "IV change",
    putCall: "Put/Call",
    unusual: "Unusual activity",
  },

  watchlists: {
    title: "Watchlists",
    create: "New watchlist",
    namePlaceholder: "Watchlist name",
    descriptionPlaceholder: "Description (optional)",
    addTicker: "Search a ticker to add",
    empty: "No watchlists yet. Create one to start tracking tickers.",
    emptyStocks: "No tickers in this watchlist.",
    rename: "Rename",
    remove: "Remove",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    price: "Price",
    dayChange: "Day",
    latestCatalyst: "Latest catalyst",
    impact: "Impact",
    confirmedDelete: "Delete this watchlist?",
  },

  alerts: {
    title: "Alerts",
    rules: "Rules",
    recent: "Recent triggers",
    create: "New rule",
    namePlaceholder: "Rule name",
    conditions: "Conditions",
    channels: "Channels",
    cooldown: "Cooldown (minutes)",
    enabled: "Enabled",
    disable: "Disable",
    enable: "Enable",
    minImpact: "Impact score at least",
    maxAge: "News age under (minutes)",
    minRvol: "RVOL at least",
    direction: "Catalyst direction",
    eventTypes: "Event types",
    tickers: "Tickers (comma separated)",
    sectors: "Sectors (comma separated)",
    changePct: "Change % at least",
    empty: "No rules yet. Create one to start matching events.",
    emptyTriggers: "No alerts triggered yet.",
    matches: "matches",
    lastTriggered: "Last triggered",
    never: "Never",
    status: "Status",
    matchedConditions: "Matched",
    triggeredAt: "Triggered",
    conditionSummaryEmpty: "No conditions",
  },

  macro: {
    title: "Macro context",
    series: "Macro series",
    heatmap: "Sector heatmap",
    breadth: "Breadth",
    advancers: "Advancers",
    decliners: "Decliners",
    regime: "Regime",
    evidence: "Evidence",
    value: "Value",
    previous: "Previous",
    change: "Change",
    asOf: "As of",
    topEvent: "Top event",
  },

  replay: {
    title: "Replay",
    date: "Date",
    scrubber: "Timeline",
    events: "Events",
    ticker: "Ticker",
    empty: "No events recorded for this date.",
    play: "Step through the day",
  },

  about: {
    title: "About MarketPulse",
    principleTitle: "The product principle",
    pipelineTitle: "The pipeline",
    weightsTitle: "Impact score weights",
    pipelineSteps: [
      "fetch_news",
      "normalize_news",
      "detect_ticker",
      "classify_event",
      "deduplicate_event",
      "fetch_market_data",
      "calculate_market_reaction",
      "calculate_impact_score",
      "evaluate_alerts",
    ],
    notes: [
      "Impact scores are computed by deterministic code, never by the language model.",
      "Sentiment is one input among many; event type, surprise and measured reaction carry more weight.",
      "Strong year-over-year growth is not automatically positive — everything is judged against expectations.",
      "Reads only read the database; all writes happen in the pipeline tick.",
    ],
  },
} as const;

export type Copy = typeof COPY;
